<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>    
    <Version>1.0.0</Version>
    <Product>Amazing.Module.EmailTemplate</Product>
    <Authors>Vineet Belani (vnetonline)</Authors>
    <Company>Amazing Software Solutions Pty Limited</Company>
    <Description>Amazing.Module.EmailTemplate is a module built for Oqtane</Description>
    <Copyright>Amazing Software Solutions Pty Limited</Copyright>
    <AssemblyName>Amazing.Module.EmailTemplate.Shared.Oqtane</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Oqtane.Shared"><HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\net10.0\Oqtane.Shared.dll</HintPath></Reference>
  </ItemGroup>

</Project>
